# Generated by Django 4.2.17 on 2024-12-16 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='giftlist',
            old_name='giftlistID',
            new_name='giftlist_id',
        ),
        migrations.RenameField(
            model_name='giftlist',
            old_name='userID',
            new_name='user',
        ),
        migrations.AddField(
            model_name='giftlist',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='giftlist',
            name='person_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='giftlist',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('giftlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftlist', to='giftlist.giftlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
